### ISSUE TITLE
Input queue full?

### ISSUE THREAD

**Issue by jrb0001** [SolraBizna/jarm#1]
If I start the tetris example with `java -jar ../OCARMsim-0.0a3a.jar -screen 2 -memory 256 -addrinfocmd "arm-none-eabi-addr2line -spfe bin/tetris.elf" -rom bin/tetris.rom` and press any key for 3 seconds, an exception is thrown while tetris is sleeping for `2147483647` (2^31-1).

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: Queue full
    at java.util.AbstractQueue.add(AbstractQueue.java:98)
    at java.util.concurrent.ArrayBlockingQueue.add(ArrayBlockingQueue.java:312)
    at name.bizna.ocarmsim.FakeMachine.signal(FakeMachine.java:164)
    at name.bizna.ocarmsim.SimUI.keyReleased(SimUI.java:248)
    at java.awt.Component.processKeyEvent(Component.java:6496)
    at javax.swing.JComponent.processKeyEvent(JComponent.java:2832)
    at java.awt.Component.processEvent(Component.java:6312)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
    at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
    at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
    at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
    at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
    at java.awt.Component.dispatchEventImpl(Component.java:4762)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by SolraBizna** [comment]
That means that your key repeat rate is higher than the rate at which Tetris was able to process signals, and the signal queue filled up. Did the exception terminate the simulator?

**Comment by jrb0001** [comment]
No, the it doesn't terminate the simulator, it throws a new exception for each key press / release / repeat. I think it should signal it to the CPU instead of throwing an exception if the signal queue is full (interrupt? flag? something else?).

**Comment by SolraBizna** [comment]
The signal queue is 32 signals deep. If the simulated computer is that far behind on signals, there's no reasonable out-of-band way for it to deal with the new signal. 32 is an arbitrary number, chosen to permit >10 characters of typeahead before problems begin. There isn't much reason to have a larger number, at least not in the simulator; allowing more typeahead just allows the computer to get farther and farther behind. Ideally the queue depth would be the same as for OpenComputers, but I don't know what queue depth it uses.

A well-written signal processing loop will consume all available signals more or less as quickly as possible. If it performs a blocking signal pop and a signal is waiting, it immediately succeeds, otherwise it is suspended until the earliest possible moment after a signal becomes available. (As if it were an OS routine waiting for an interrupt.) I don't remember whether Tetris's signal processing loop was well-written or not, but I'd be willing to give past-Solra the benefit of the doubt.

I'd be open to the idea of adding some kind of "signals have been lost" flag so that software can detect when this situation has happened. It would be pretty simple to implement in the simulator, I'm just not sure about making it reliably work in OpenComputers. Having this flag would at least permit some level of intelligent recovery on the part of well-written programs... instead of having the signal stream lose cohesion with no hope of detection or recovery.

Regardless, I should handle that particular exception and provide a more... relevant message, such as "Signal queue overflow! Signals are being lost!"

**Comment by jrb0001** [comment]
Signals are currently consumed by polling, right? What about an interrupt mode (disabled on boot)? Assignable interrupt priority per signal type would be a bonus but not that important. To make it work reliably, just move the signals from the oc queue to your own queue and generate an interrupt if enabled before each instruction / group of instructions. The queue size looks right, a depth of more than 32 signals shouldn't be needed (unless on heavy (peripheral) load).

The problem with Tetris's signal processing is that it goes into a very long sleep. I will check that bug but it might take a while.

**Comment by SolraBizna** [comment]
Sleeps in progress get cancelled when a signal arrives, and don't even start if the queue isn't empty to begin with. The long sleep is an idiom for "sleep until a signal arrives". Tetris consumes signals by polling in a tight loop, so it can't consume them any faster than it does.

I did plan to eventually add signals-as-interrupts as you describe, but ran out of time before I could get that far. (A "serious" OS would pretty much require it.)
